#!/bin/bash
#
# Init script for Kibana
#
# chkconfig: - 85 15
# description: Init script for kibana

### BEGIN INIT INFO
# Provides: Kibana
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Kibana
# Description: Kibana is a webfront end for Elasticsearch
### END INIT INFO


# Source function library.
. /etc/rc.d/init.d/functions


DAEMON='/usr/local/kibana/kibana-daemon.rb'

start() {
        echo -n $"Starting Kibana: "

        ruby $DAEMON start
        RETVAL=$?

        if [ $RETVAL = 0 ]; then
            echo_success
        else
            echo_failure
        fi

        echo
        return $RETVAL
}

stop() {
        echo -n $"Stopping Kibana: "
        ruby $DAEMON stop
        RETVAL=$?
        if [ $RETVAL = 0 ]; then
            echo_success
        else
            echo_failure
        fi

        rm -rf /usr/local/kibana/tmp/kibana.rb.pid

        echo
        return $RETVAL
}

restart () {
        stop
        start
}

status () {
        ruby $DAEMON status
        RETVAL=$?
        return $RETVAL
}

force_reload () {
        restart
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    force-reload)
        force_reload
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|force-reload}"
        exit 2
esac

exit $?
